FROM mcr.microsoft.com/devcontainers/rust:1-1-bullseye
USER vscode
WORKDIR /workspace/gbt
RUN sudo rm /var/lib/apt/lists/* -vf
RUN sudo apt -y update
RUN sudo apt -y install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    file \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev
RUN sudo rm -rf /var/lib/apt/lists/*
RUN sudo curl https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz --output node.tar.xz && \
    sudo mkdir -p /usr/local/lib/nodejs && \
    sudo tar -xJvf node.tar.xz -C /usr/local/lib/nodejs && \
    export PATH=/usr/local/lib/nodejs/node-v20.11.1-linux-x64/bin:$PATH && \
    npm install -g typescript
ENV PATH="${PATH}:/usr/local/lib/nodejs/node-v20.11.1-linux-x64/bin"

RUN cargo install tauri-cli
